export type Difficulty = "Beginner" | "Intermediate" | "Advanced" | "Elite"

export type ProgressionType = "Bodyweight" | "Band" | "Weighted" | "Plyometric"

export interface Exercise {
  id: number
  name: string
  category: string
  subcategory: string
  progressionType: ProgressionType
  difficulty: Difficulty
  equipment: string[]
  primaryMuscles: string[]
  secondaryMuscles: string[]
}

export const exercises: Exercise[] = [
  {
    id: 1,
    name: "Wall Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus"],
  },
  {
    id: 2,
    name: "Knee Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus", "abs"],
  },
  {
    id: 3,
    name: "Incline Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Bench/Surface"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus"],
  },
  {
    id: 4,
    name: "Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus"],
  },
  {
    id: 5,
    name: "Wide Grip Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["chest", "front_shoulder"],
    secondaryMuscles: ["triceps", "serratus"],
  },
  {
    id: 6,
    name: "Close Grip Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_shoulder"],
  },
  {
    id: 7,
    name: "Diamond Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_shoulder"],
  },
  {
    id: 8,
    name: "Decline Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench/Surface"],
    primaryMuscles: ["chest", "front_shoulder", "triceps"],
    secondaryMuscles: ["serratus"],
  },
  {
    id: 9,
    name: "Staggered Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "serratus"],
  },
  {
    id: 10,
    name: "Reverse Grip Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "biceps", "front_shoulder"],
    secondaryMuscles: ["forearms"],
  },
  {
    id: 11,
    name: "Hands Release Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["lower_back", "glutes"],
  },
  {
    id: 12,
    name: "Push-Up With Single Leg Raise",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["glutes", "abs", "obliques"],
  },
  {
    id: 13,
    name: "Elevated Push-Up (Parallettes)",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Parallettes"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus", "abs"],
  },
  {
    id: 14,
    name: "Uneven Push-Up on Bench",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques"],
  },
  {
    id: 15,
    name: "Uneven Push-Up on Medicine Ball",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Medicine Ball"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "abs"],
  },
  {
    id: 16,
    name: "Stability Ball Decline Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Stability Ball"],
    primaryMuscles: ["chest", "front_shoulder", "triceps"],
    secondaryMuscles: ["abs", "glutes"],
  },
  {
    id: 17,
    name: "Stability Ball Incline Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Stability Ball"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 18,
    name: "Single-Arm Push-Up on Knees",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "abs"],
  },
  {
    id: 19,
    name: "Renegade Row Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Dumbbells"],
    primaryMuscles: ["chest", "triceps", "lats"],
    secondaryMuscles: ["obliques", "biceps", "abs"],
  },
  {
    id: 20,
    name: "Knee Drive Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["hip_flexors", "abs"],
  },
  {
    id: 21,
    name: "Sphinx Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_shoulder", "abs"],
  },
  {
    id: 22,
    name: "Resistance Band Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus", "abs"],
  },
  {
    id: 23,
    name: "Weighted Vest Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Weight Vest"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus"],
  },
  {
    id: 24,
    name: "Clap Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 25,
    name: "Chest Tap Plyo Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 26,
    name: "Spiderman Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "hip_flexors", "abs"],
  },
  {
    id: 27,
    name: "Decline Push-Up Depth Jump",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: ["Bench"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 28,
    name: "T Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "side_shoulder"],
  },
  {
    id: 29,
    name: "Typewriter Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_shoulder", "side_shoulder"],
  },
  {
    id: 30,
    name: "Hindu Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "front_shoulder", "triceps"],
    secondaryMuscles: ["lower_back", "abs", "hip_flexors"],
  },
  {
    id: 31,
    name: "Archer Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["biceps", "serratus"],
  },
  {
    id: 32,
    name: "Cross Arm Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_shoulder", "obliques"],
  },
  {
    id: 33,
    name: "Fingertip Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "forearms"],
    secondaryMuscles: ["front_shoulder"],
  },
  {
    id: 34,
    name: "Superman Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Plyometric",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 35,
    name: "Single Arm Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "abs", "serratus"],
  },
  {
    id: 36,
    name: "Pike to Cobra Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["front_shoulder", "chest", "triceps"],
    secondaryMuscles: ["lower_back", "abs"],
  },
  {
    id: 37,
    name: "Close-Grip Single Dumbbell Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Dumbbell"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_shoulder", "abs"],
  },
  {
    id: 38,
    name: "Single-Arm Push-Up on Medicine Ball",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Medicine Ball"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "abs"],
  },
  {
    id: 39,
    name: "Band-Assisted One-Arm Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Band",
    difficulty: "Advanced",
    equipment: ["Resistance Band"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques"],
  },
  {
    id: 40,
    name: "Weighted Push-Up (Plate on Back)",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Weight Plate"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus"],
  },
  // ── PUSH → DIPS ─────────────────────────────────────────────────────────
  {
    id: 41,
    name: "Bench Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Bench"],
    primaryMuscles: ["triceps", "chest", "front_shoulder"],
    secondaryMuscles: [],
  },
  {
    id: 42,
    name: "Parallel Bar Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Parallel Bars"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus"],
  },
  {
    id: 43,
    name: "Ring Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus"],
  },
  {
    id: 44,
    name: "Weighted Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Parallel Bars", "Weight Belt"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus"],
  },
  {
    id: 45,
    name: "Band-Assisted Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Parallel Bars", "Resistance Band"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: [],
  },
  {
    id: 46,
    name: "Korean Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallel Bars"],
    primaryMuscles: ["rear_shoulder", "triceps", "chest"],
    secondaryMuscles: ["lower_back"],
  },
  {
    id: 47,
    name: "Russian Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallel Bars"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["forearms", "abs"],
  },
  {
    id: 48,
    name: "L-Sit Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallel Bars"],
    primaryMuscles: ["chest", "triceps", "abs", "hip_flexors"],
    secondaryMuscles: ["front_shoulder", "quads"],
  },
  // ── PUSH → HANDSTAND / OVERHEAD ────────────────────────────────────────
  {
    id: 49,
    name: "Pike Push-Up",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["chest", "upper_back"],
  },
  {
    id: 50,
    name: "Elevated Pike Push-Up",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench/Surface"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["chest"],
  },
  {
    id: 51,
    name: "Wall Handstand Hold",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Wall"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["abs", "upper_back", "serratus"],
  },
  {
    id: 52,
    name: "Handstand Push-Up Negative",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Wall"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["upper_back", "abs"],
  },
  {
    id: 53,
    name: "Handstand Push-Up",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Wall"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["upper_back", "abs", "serratus"],
  },
  {
    id: 54,
    name: "Deficit Handstand Push-Up",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Wall", "Parallettes"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["upper_back", "abs"],
  },
  {
    id: 55,
    name: "Freestanding Handstand Push-Up",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["abs", "upper_back", "serratus", "forearms"],
  },
  {
    id: 56,
    name: "Band-Assisted HSPU",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Wall", "Resistance Band"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["upper_back"],
  },
  // ── PULL → PULL-UP ──────────────────────────────────────────────────────
  {
    id: 57,
    name: "Dead Hang",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["forearms", "lats"],
    secondaryMuscles: ["biceps", "upper_back"],
  },
  {
    id: 58,
    name: "Active Hang / Scapular Pull",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["upper_back", "lats", "rear_shoulder"],
    secondaryMuscles: ["forearms"],
  },
  {
    id: 59,
    name: "Band-Assisted Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar", "Resistance Band"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["rear_shoulder", "forearms"],
  },
  {
    id: 60,
    name: "Negative Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "rear_shoulder"],
  },
  {
    id: 61,
    name: "Chin-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["biceps", "lats", "upper_back"],
    secondaryMuscles: ["forearms", "rear_shoulder"],
  },
  {
    id: 62,
    name: "Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["forearms", "rear_shoulder"],
  },
  {
    id: 63,
    name: "Wide Grip Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps", "rear_shoulder", "forearms"],
  },
  {
    id: 64,
    name: "Neutral Grip Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms"],
  },
  {
    id: 65,
    name: "Commando Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "obliques"],
  },
  {
    id: 66,
    name: "L-Sit Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "hip_flexors", "biceps"],
    secondaryMuscles: ["upper_back", "quads", "forearms"],
  },
  {
    id: 67,
    name: "Weighted Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar", "Weight Belt"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "rear_shoulder"],
  },
  {
    id: 68,
    name: "Typewriter Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "obliques"],
  },
  {
    id: 69,
    name: "Archer Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "side_shoulder"],
  },
  {
    id: 70,
    name: "One-Arm Assisted Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back", "forearms"],
  },
  {
    id: 71,
    name: "One-Arm Pull-Up Negative",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back", "forearms", "obliques"],
  },
  {
    id: 72,
    name: "One-Arm Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "forearms"],
    secondaryMuscles: ["upper_back", "obliques"],
  },
  {
    id: 73,
    name: "Weighted Chin-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar", "Weight Belt"],
    primaryMuscles: ["biceps", "lats", "upper_back"],
    secondaryMuscles: ["forearms"],
  },
  // ── PULL → MUSCLE-UP ────────────────────────────────────────────────────
  {
    id: 74,
    name: "Muscle-Up Kipping",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["upper_back", "abs", "front_shoulder"],
  },
  {
    id: 75,
    name: "Muscle-Up Strict",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["upper_back", "front_shoulder", "abs"],
  },
  {
    id: 76,
    name: "Ring Muscle-Up",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["abs", "front_shoulder", "upper_back", "serratus"],
  },
  // ── PULL → ROWS ─────────────────────────────────────────────────────────
  {
    id: 77,
    name: "Table Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Table"],
    primaryMuscles: ["upper_back", "biceps", "rear_shoulder"],
    secondaryMuscles: ["forearms", "abs"],
  },
  {
    id: 78,
    name: "Australian Pull-Up / Inverted Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Bar/Table"],
    primaryMuscles: ["upper_back", "lats", "biceps", "rear_shoulder"],
    secondaryMuscles: ["forearms", "abs"],
  },
  {
    id: 79,
    name: "Feet-Elevated Inverted Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bar"],
    primaryMuscles: ["upper_back", "lats", "biceps", "rear_shoulder"],
    secondaryMuscles: ["abs", "hamstrings"],
  },
  {
    id: 80,
    name: "Ring Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["upper_back", "biceps", "rear_shoulder", "lats"],
    secondaryMuscles: ["forearms", "abs"],
  },
  {
    id: 81,
    name: "Single-Arm Ring Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["obliques", "forearms"],
  },
  {
    id: 82,
    name: "Band Face Pull",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["rear_shoulder", "upper_back"],
    secondaryMuscles: ["side_shoulder", "biceps"],
  },
  {
    id: 83,
    name: "Band Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["upper_back", "lats", "biceps", "rear_shoulder"],
    secondaryMuscles: ["forearms"],
  },
  {
    id: 84,
    name: "Weighted Vest Inverted Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Bar", "Weight Vest"],
    primaryMuscles: ["upper_back", "lats", "biceps", "rear_shoulder"],
    secondaryMuscles: ["abs"],
  },
  // ── LEGS → SQUATS ───────────────────────────────────────────────────────
  {
    id: 85,
    name: "Assisted Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Support"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 86,
    name: "Bodyweight Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs", "lower_back"],
  },
  {
    id: 87,
    name: "Sumo Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  {
    id: 88,
    name: "Jump Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 89,
    name: "Bulgarian Split Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 90,
    name: "Sissy Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["calves", "abs"],
  },
  {
    id: 91,
    name: "Pistol Squat Assisted",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Support"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs", "hip_flexors"],
  },
  {
    id: 92,
    name: "Pistol Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs", "hip_flexors"],
  },
  {
    id: 93,
    name: "Weighted Pistol Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Weighted",
    difficulty: "Elite",
    equipment: ["Weight Vest"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 94,
    name: "Band Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  {
    id: 95,
    name: "Box Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Box/Bench"],
    primaryMuscles: ["quads", "glutes", "hamstrings"],
    secondaryMuscles: ["calves", "abs", "lower_back"],
  },
  {
    id: 96,
    name: "Shrimp Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "hip_flexors"],
  },
  {
    id: 97,
    name: "Weighted Vest Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Weight Vest"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "lower_back"],
  },
  // ── LEGS → LUNGES ───────────────────────────────────────────────────────
  {
    id: 98,
    name: "Reverse Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 99,
    name: "Forward Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  {
    id: 100,
    name: "Walking Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 101,
    name: "Lateral Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["hamstrings"],
  },
  {
    id: 102,
    name: "Curtsy Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["hamstrings", "obliques"],
  },
  {
    id: 103,
    name: "Jumping Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 104,
    name: "Weighted Vest Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Weight Vest"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  // ── LEGS → HIP HINGE / GLUTE ────────────────────────────────────────────
  {
    id: 105,
    name: "Glute Bridge",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["abs", "lower_back"],
  },
  {
    id: 106,
    name: "Hip Thrust (Bodyweight)",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Bench"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["quads", "abs", "lower_back"],
  },
  {
    id: 107,
    name: "Single-Leg Glute Bridge",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["abs", "lower_back", "obliques"],
  },
  {
    id: 108,
    name: "Nordic Hamstring Curl",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Support to anchor feet"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "calves", "lower_back"],
  },
  {
    id: 109,
    name: "Band Hamstring Curl",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "calves"],
  },
  {
    id: 110,
    name: "Donkey Kick",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower_back"],
  },
  {
    id: 111,
    name: "Fire Hydrant",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["obliques", "hip_flexors"],
  },
  {
    id: 112,
    name: "Good Morning (Bodyweight)",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["hamstrings", "lower_back", "glutes"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 113,
    name: "Band Hip Thrust",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band", "Bench"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["quads", "abs"],
  },
  {
    id: 114,
    name: "Weighted Glute Bridge",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Weight Plate"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["abs", "lower_back"],
  },
  // ── LEGS → CALVES ───────────────────────────────────────────────────────
  {
    id: 115,
    name: "Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  {
    id: 116,
    name: "Single-Leg Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  {
    id: 117,
    name: "Elevated Single-Leg Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Step/Ledge"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  {
    id: 118,
    name: "Explosive Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["calves"],
    secondaryMuscles: ["quads"],
  },
  {
    id: 119,
    name: "Weighted Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Weight Vest"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  // ── CORE → PLANK ────────────────────────────────────────────────────────
  {
    id: 120,
    name: "Forearm Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "obliques"],
    secondaryMuscles: ["glutes", "lower_back", "serratus"],
  },
  {
    id: 121,
    name: "High Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "obliques", "serratus"],
    secondaryMuscles: ["chest", "front_shoulder", "glutes", "lower_back"],
  },
  {
    id: 122,
    name: "Side Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["glutes", "side_shoulder", "lats"],
  },
  {
    id: 123,
    name: "Side Plank with Hip Dip",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["glutes", "lats"],
  },
  {
    id: 124,
    name: "Plank Shoulder Tap",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "obliques", "front_shoulder"],
    secondaryMuscles: ["chest", "serratus", "glutes"],
  },
  {
    id: 125,
    name: "Plank Up-Downs",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "triceps", "front_shoulder"],
    secondaryMuscles: ["obliques", "chest", "glutes"],
  },
  {
    id: 126,
    name: "Single-Leg Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "glutes", "obliques"],
    secondaryMuscles: ["lower_back", "hamstrings"],
  },
  {
    id: 127,
    name: "Weighted Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Weight Plate/Vest"],
    primaryMuscles: ["abs", "obliques"],
    secondaryMuscles: ["glutes", "lower_back"],
  },
  {
    id: 128,
    name: "Plank to Downward Dog",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "front_shoulder", "serratus"],
    secondaryMuscles: ["hamstrings", "upper_back"],
  },
  // ── CORE → L-SIT ────────────────────────────────────────────────────────
  {
    id: 129,
    name: "Tuck Hold (Floor)",
    category: "Core",
    subcategory: "L-Sit",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "triceps", "front_shoulder"],
    secondaryMuscles: ["chest", "quads", "forearms"],
  },
  {
    id: 130,
    name: "Advanced Tuck L-Sit",
    category: "Core",
    subcategory: "L-Sit",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Parallettes"],
    primaryMuscles: ["abs", "hip_flexors", "triceps"],
    secondaryMuscles: ["quads", "chest", "front_shoulder", "forearms"],
  },
  {
    id: 131,
    name: "L-Sit",
    category: "Core",
    subcategory: "L-Sit",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallettes/Bar"],
    primaryMuscles: ["abs", "hip_flexors", "quads", "triceps"],
    secondaryMuscles: ["chest", "front_shoulder", "forearms"],
  },
  {
    id: 132,
    name: "Straddle L-Sit",
    category: "Core",
    subcategory: "L-Sit",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallettes/Bar"],
    primaryMuscles: ["abs", "hip_flexors", "triceps"],
    secondaryMuscles: ["quads", "chest", "forearms"],
  },
  {
    id: 133,
    name: "V-Sit",
    category: "Core",
    subcategory: "L-Sit",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "quads"],
    secondaryMuscles: ["triceps", "chest", "forearms", "lower_back"],
  },
  // ── CORE → DRAGON FLAG ──────────────────────────────────────────────────
  {
    id: 134,
    name: "Reverse Crunch",
    category: "Core",
    subcategory: "Dragon Flag",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques"],
  },
  {
    id: 135,
    name: "Tuck Dragon Flag",
    category: "Core",
    subcategory: "Dragon Flag",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench/Pole"],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques", "lower_back"],
  },
  {
    id: 136,
    name: "Dragon Flag Negative",
    category: "Core",
    subcategory: "Dragon Flag",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Bench/Pole"],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques", "lower_back", "serratus"],
  },
  {
    id: 137,
    name: "Dragon Flag",
    category: "Core",
    subcategory: "Dragon Flag",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Bench/Pole"],
    primaryMuscles: ["abs", "hip_flexors", "serratus"],
    secondaryMuscles: ["obliques", "lower_back", "quads"],
  },
  // ── CORE → LEG RAISES ───────────────────────────────────────────────────
  {
    id: 138,
    name: "Lying Leg Raise",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques", "quads"],
  },
  {
    id: 139,
    name: "Hanging Knee Raise",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["forearms", "obliques"],
  },
  {
    id: 140,
    name: "Hanging Leg Raise",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["quads", "forearms", "obliques"],
  },
  {
    id: 141,
    name: "Toes to Bar",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["abs", "hip_flexors", "lats"],
    secondaryMuscles: ["quads", "forearms", "obliques"],
  },
  {
    id: 142,
    name: "Windshield Wipers",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["obliques", "abs", "hip_flexors"],
    secondaryMuscles: ["lats", "forearms", "quads"],
  },
  {
    id: 143,
    name: "Hanging L-Sit Hold",
    category: "Core",
    subcategory: "Leg Raise",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["abs", "hip_flexors", "quads", "forearms"],
    secondaryMuscles: ["lats", "obliques"],
  },
  // ── CORE → AB WHEEL ─────────────────────────────────────────────────────
  {
    id: 144,
    name: "Kneeling Ab Wheel Rollout",
    category: "Core",
    subcategory: "Ab Wheel",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Ab Wheel"],
    primaryMuscles: ["abs", "serratus"],
    secondaryMuscles: ["lats", "lower_back", "triceps", "front_shoulder"],
  },
  {
    id: 145,
    name: "Standing Ab Wheel Rollout",
    category: "Core",
    subcategory: "Ab Wheel",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Ab Wheel"],
    primaryMuscles: ["abs", "serratus", "lats"],
    secondaryMuscles: ["lower_back", "triceps", "front_shoulder", "hip_flexors"],
  },
  {
    id: 146,
    name: "Single-Arm Ab Wheel Rollout",
    category: "Core",
    subcategory: "Ab Wheel",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Ab Wheel"],
    primaryMuscles: ["abs", "obliques", "serratus"],
    secondaryMuscles: ["lats", "triceps", "lower_back"],
  },
  // ── CORE → STATIC HOLD ──────────────────────────────────────────────────
  {
    id: 147,
    name: "Hollow Body Hold",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "serratus"],
    secondaryMuscles: ["quads", "obliques"],
  },
  {
    id: 148,
    name: "Arch Hold",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings", "rear_shoulder", "upper_back"],
  },
  {
    id: 149,
    name: "Bicycle Crunch",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["obliques", "abs", "hip_flexors"],
    secondaryMuscles: ["quads"],
  },
  {
    id: 150,
    name: "Mountain Climbers",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "front_shoulder"],
    secondaryMuscles: ["quads", "chest", "triceps", "obliques"],
  },
  {
    id: 151,
    name: "Russian Twist",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["hip_flexors"],
  },
  {
    id: 152,
    name: "Human Flag Progression",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Vertical Pole"],
    primaryMuscles: ["obliques", "lats", "abs"],
    secondaryMuscles: ["side_shoulder", "upper_back", "hip_flexors", "glutes"],
  },
  // ── FULL BODY ────────────────────────────────────────────────────────────
  {
    id: 153,
    name: "Burpee",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["chest", "quads", "glutes", "abs"],
    secondaryMuscles: ["triceps", "front_shoulder", "hamstrings", "calves"],
  },
  {
    id: 154,
    name: "Burpee Pull-Up",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["chest", "quads", "glutes", "lats", "biceps"],
    secondaryMuscles: ["triceps", "front_shoulder", "abs", "hamstrings"],
  },
  {
    id: 155,
    name: "Bear Crawl",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["front_shoulder", "chest", "abs", "quads"],
    secondaryMuscles: ["triceps", "hip_flexors", "obliques"],
  },
  {
    id: 156,
    name: "Crab Walk",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["triceps", "glutes", "front_shoulder"],
    secondaryMuscles: ["hamstrings", "abs", "upper_back"],
  },
  {
    id: 157,
    name: "Inchworm",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "front_shoulder", "hamstrings"],
    secondaryMuscles: ["chest", "triceps", "calves"],
  },
  {
    id: 158,
    name: "Broad Jump",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "abs"],
  },
  {
    id: 159,
    name: "Burpee Box Jump",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: ["Box"],
    primaryMuscles: ["quads", "glutes", "chest", "calves"],
    secondaryMuscles: ["triceps", "front_shoulder", "abs", "hamstrings"],
  },

  // ════════════════════════════════════════════════════════════════════════
  // NEW EXERCISES — IDs 160 onwards
  // ════════════════════════════════════════════════════════════════════════

  // ── PUSH → PUSH-UP (new) ────────────────────────────────────────────────
  {
    id: 160,
    name: "Pseudo Planche Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["chest", "front_shoulder", "serratus"],
    secondaryMuscles: ["triceps", "abs", "wrist_flexors"],
  },
  {
    id: 161,
    name: "Ring Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus", "abs", "forearms"],
  },
  {
    id: 162,
    name: "Wide Ring Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "front_shoulder"],
    secondaryMuscles: ["triceps", "serratus", "forearms"],
  },
  {
    id: 163,
    name: "Parallette L-Sit Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallettes"],
    primaryMuscles: ["chest", "triceps", "abs", "hip_flexors"],
    secondaryMuscles: ["front_shoulder", "quads", "serratus"],
  },
  {
    id: 164,
    name: "Behind-the-Back Clap Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Plyometric",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "rear_shoulder"],
  },
  {
    id: 165,
    name: "90-Degree Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallettes"],
    primaryMuscles: ["chest", "triceps", "serratus", "front_shoulder"],
    secondaryMuscles: ["abs", "forearms", "wrist_flexors"],
  },
  {
    id: 166,
    name: "Knuckle Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["forearms", "serratus"],
  },
  {
    id: 167,
    name: "Tuck Planche Push-Up",
    category: "Push",
    subcategory: "Push-Up",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallettes"],
    primaryMuscles: ["chest", "front_shoulder", "triceps", "serratus"],
    secondaryMuscles: ["abs", "wrist_flexors", "forearms"],
  },

  // ── PUSH → DIPS (new) ───────────────────────────────────────────────────
  {
    id: 168,
    name: "Chair Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Chair"],
    primaryMuscles: ["triceps", "front_shoulder"],
    secondaryMuscles: ["chest"],
  },
  {
    id: 169,
    name: "Straight Bar Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus"],
  },
  {
    id: 170,
    name: "Weighted Ring Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Weighted",
    difficulty: "Elite",
    equipment: ["Gymnastic Rings", "Weight Belt"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus", "forearms"],
  },
  {
    id: 171,
    name: "Negative Ring Dip",
    category: "Push",
    subcategory: "Dip",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["serratus", "abs"],
  },

  // ── PUSH → OVERHEAD (new) ───────────────────────────────────────────────
  {
    id: 172,
    name: "Crow Pose Hold",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["front_shoulder", "triceps", "abs"],
    secondaryMuscles: ["chest", "forearms", "hip_flexors"],
  },
  {
    id: 173,
    name: "Headstand Hold",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["abs", "upper_back", "neck"],
  },
  {
    id: 174,
    name: "Freestanding Handstand Hold",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["abs", "serratus", "forearms", "wrist_flexors"],
  },
  {
    id: 175,
    name: "Handstand Walk",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["abs", "serratus", "forearms", "upper_back"],
  },
  {
    id: 176,
    name: "Pike Push-Up on Parallettes",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["chest", "serratus"],
  },
  {
    id: 177,
    name: "Band Lateral Raise",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["side_shoulder"],
    secondaryMuscles: ["front_shoulder", "upper_back"],
  },
  {
    id: 178,
    name: "Band Overhead Press",
    category: "Push",
    subcategory: "Overhead",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["front_shoulder", "side_shoulder", "triceps"],
    secondaryMuscles: ["upper_back", "abs"],
  },

  // ── PUSH → PLANCHE (new subcategory) ────────────────────────────────────
  {
    id: 179,
    name: "Planche Lean",
    category: "Push",
    subcategory: "Planche",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "serratus", "chest"],
    secondaryMuscles: ["abs", "triceps", "wrist_flexors"],
  },
  {
    id: 180,
    name: "Tuck Planche Hold",
    category: "Push",
    subcategory: "Planche",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "serratus", "chest", "abs"],
    secondaryMuscles: ["triceps", "hip_flexors", "wrist_flexors"],
  },
  {
    id: 181,
    name: "Advanced Tuck Planche Hold",
    category: "Push",
    subcategory: "Planche",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "serratus", "chest"],
    secondaryMuscles: ["abs", "triceps", "hip_flexors"],
  },
  {
    id: 182,
    name: "Straddle Planche Hold",
    category: "Push",
    subcategory: "Planche",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "serratus", "chest", "abs"],
    secondaryMuscles: ["triceps", "adductors", "wrist_flexors"],
  },
  {
    id: 183,
    name: "Full Planche Hold",
    category: "Push",
    subcategory: "Planche",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Parallettes"],
    primaryMuscles: ["front_shoulder", "serratus", "chest", "abs"],
    secondaryMuscles: ["triceps", "glutes", "lower_back", "wrist_flexors"],
  },

  // ── PULL → PULL-UP (new) ────────────────────────────────────────────────
  {
    id: 184,
    name: "Close Grip Chin-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["biceps", "lats"],
    secondaryMuscles: ["upper_back", "forearms"],
  },
  {
    id: 185,
    name: "Behind-the-Neck Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["upper_back", "lats", "rear_shoulder"],
    secondaryMuscles: ["biceps", "forearms"],
  },
  {
    id: 186,
    name: "Chest-to-Bar Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["rear_shoulder", "forearms", "abs"],
  },
  {
    id: 187,
    name: "Mixed Grip Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "obliques"],
  },
  {
    id: 188,
    name: "Band-Assisted Chin-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Pull-Up Bar", "Resistance Band"],
    primaryMuscles: ["biceps", "lats", "upper_back"],
    secondaryMuscles: ["forearms"],
  },
  {
    id: 189,
    name: "Towel Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar", "Towel"],
    primaryMuscles: ["lats", "biceps", "forearms"],
    secondaryMuscles: ["upper_back", "rear_shoulder"],
  },
  {
    id: 190,
    name: "Ring Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "rear_shoulder", "serratus"],
  },
  {
    id: 191,
    name: "Weighted Ring Pull-Up",
    category: "Pull",
    subcategory: "Pull-Up",
    progressionType: "Weighted",
    difficulty: "Elite",
    equipment: ["Gymnastic Rings", "Weight Belt"],
    primaryMuscles: ["lats", "biceps", "upper_back"],
    secondaryMuscles: ["forearms", "rear_shoulder"],
  },

  // ── PULL → MUSCLE-UP (new) ──────────────────────────────────────────────
  {
    id: 192,
    name: "Muscle-Up Transition Drill",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["upper_back", "front_shoulder"],
  },
  {
    id: 193,
    name: "Band-Assisted Muscle-Up",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar", "Resistance Band"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["upper_back", "front_shoulder"],
  },
  {
    id: 194,
    name: "Weighted Bar Muscle-Up",
    category: "Pull",
    subcategory: "Muscle-Up",
    progressionType: "Weighted",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar", "Weight Belt"],
    primaryMuscles: ["lats", "biceps", "chest", "triceps"],
    secondaryMuscles: ["abs", "front_shoulder", "upper_back"],
  },

  // ── PULL → ROW (new) ────────────────────────────────────────────────────
  {
    id: 195,
    name: "Tuck Front Lever Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["abs", "rear_shoulder", "forearms"],
  },
  {
    id: 196,
    name: "Band Pull-Apart",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["rear_shoulder", "upper_back"],
    secondaryMuscles: ["side_shoulder"],
  },
  {
    id: 197,
    name: "Pronated Inverted Row",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bar"],
    primaryMuscles: ["upper_back", "lats", "rear_shoulder"],
    secondaryMuscles: ["forearms", "biceps", "abs"],
  },
  {
    id: 198,
    name: "Ring Chest Fly",
    category: "Pull",
    subcategory: "Row",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "front_shoulder"],
    secondaryMuscles: ["biceps", "serratus"],
  },

  // ── PULL → FRONT LEVER (new subcategory) ────────────────────────────────
  {
    id: 199,
    name: "Tuck Front Lever Hold",
    category: "Pull",
    subcategory: "Front Lever",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "rear_shoulder"],
    secondaryMuscles: ["upper_back", "hip_flexors", "forearms"],
  },
  {
    id: 200,
    name: "Advanced Tuck Front Lever Hold",
    category: "Pull",
    subcategory: "Front Lever",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "rear_shoulder"],
    secondaryMuscles: ["upper_back", "forearms", "hip_flexors"],
  },
  {
    id: 201,
    name: "Straddle Front Lever Hold",
    category: "Pull",
    subcategory: "Front Lever",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "rear_shoulder", "upper_back"],
    secondaryMuscles: ["obliques", "forearms", "adductors"],
  },
  {
    id: 202,
    name: "Full Front Lever Hold",
    category: "Pull",
    subcategory: "Front Lever",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "rear_shoulder", "upper_back"],
    secondaryMuscles: ["obliques", "glutes", "forearms", "hip_flexors"],
  },
  {
    id: 203,
    name: "Front Lever Raise",
    category: "Pull",
    subcategory: "Front Lever",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["lats", "abs", "rear_shoulder", "upper_back"],
    secondaryMuscles: ["hip_flexors", "forearms", "glutes"],
  },

  // ── LEGS → SQUAT (new) ──────────────────────────────────────────────────
  {
    id: 204,
    name: "Wall Sit",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Wall"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 205,
    name: "Narrow Stance Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "calves", "abs"],
  },
  {
    id: 206,
    name: "Pulse Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  {
    id: 207,
    name: "Skater Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs", "hip_flexors"],
  },
  {
    id: 208,
    name: "Dragon Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "hip_flexors"],
    secondaryMuscles: ["hamstrings", "obliques", "abs"],
  },
  {
    id: 209,
    name: "Band Bulgarian Split Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band", "Bench"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 210,
    name: "Cossack Squat",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["hamstrings", "calves", "hip_flexors"],
  },
  {
    id: 211,
    name: "Box Jump",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: ["Box"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "abs"],
  },
  {
    id: 212,
    name: "Depth Jump",
    category: "Legs",
    subcategory: "Squat",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: ["Box"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "abs"],
  },

  // ── LEGS → LUNGE (new) ──────────────────────────────────────────────────
  {
    id: 213,
    name: "Rear-Foot Elevated Split Squat Pulse",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Bench"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },
  {
    id: 214,
    name: "Diagonal Lunge",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors", "hamstrings", "calves"],
  },
  {
    id: 215,
    name: "Jumping Split Squat",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 216,
    name: "Weighted Vest Split Squat",
    category: "Legs",
    subcategory: "Lunge",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Weight Vest"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },

  // ── LEGS → HIP HINGE (new) ──────────────────────────────────────────────
  {
    id: 217,
    name: "Hip Hinge (Deadlift Pattern)",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["hamstrings", "glutes", "lower_back"],
    secondaryMuscles: ["abs", "calves"],
  },
  {
    id: 218,
    name: "Single-Leg Romanian Deadlift",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "abs", "calves"],
  },
  {
    id: 219,
    name: "Glute Kickback with Band",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower_back"],
  },
  {
    id: 220,
    name: "Stability Ball Hamstring Curl",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Stability Ball"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["calves", "abs", "lower_back"],
  },
  {
    id: 221,
    name: "Frog Pump",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["adductors", "abs"],
  },
  {
    id: 222,
    name: "Cook Hip Lift",
    category: "Legs",
    subcategory: "Hip Hinge",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["abs", "hip_flexors"],
  },

  // ── LEGS → CALVES (new) ─────────────────────────────────────────────────
  {
    id: 223,
    name: "Seated Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  {
    id: 224,
    name: "Band Calf Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Band",
    difficulty: "Beginner",
    equipment: ["Resistance Band"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
  },
  {
    id: 225,
    name: "Jump Rope (Double Unders)",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: ["Jump Rope"],
    primaryMuscles: ["calves"],
    secondaryMuscles: ["quads", "abs", "forearms"],
  },
  {
    id: 226,
    name: "Tibialis Raise",
    category: "Legs",
    subcategory: "Calves",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Wall"],
    primaryMuscles: ["tibialis"],
    secondaryMuscles: [],
  },

  // ── LEGS → PLYOMETRICS (new subcategory) ────────────────────────────────
  {
    id: 227,
    name: "Tuck Jump",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["abs", "hip_flexors", "hamstrings"],
  },
  {
    id: 228,
    name: "Single-Leg Broad Jump",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "abs"],
  },
  {
    id: 229,
    name: "Lateral Bound",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["glutes", "quads", "adductors"],
    secondaryMuscles: ["calves", "hamstrings", "abs"],
  },
  {
    id: 230,
    name: "Depth Drop",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: ["Box"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 231,
    name: "Skater Jump",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["adductors", "calves", "abs"],
  },
  {
    id: 232,
    name: "180 Jump Squat",
    category: "Legs",
    subcategory: "Plyometrics",
    progressionType: "Plyometric",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["abs", "obliques", "hamstrings"],
  },

  // ── CORE → PLANK (new) ──────────────────────────────────────────────────
  {
    id: 233,
    name: "RKC Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["obliques", "quads", "front_shoulder"],
  },
  {
    id: 234,
    name: "Plank Reach-Out",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "serratus", "front_shoulder"],
    secondaryMuscles: ["obliques", "glutes", "upper_back"],
  },
  {
    id: 235,
    name: "Side Plank Star",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: [],
    primaryMuscles: ["obliques", "abs", "glutes"],
    secondaryMuscles: ["side_shoulder", "adductors", "lats"],
  },
  {
    id: 236,
    name: "Plank Pike",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "front_shoulder"],
    secondaryMuscles: ["serratus", "hamstrings"],
  },
  {
    id: 237,
    name: "Stability Ball Plank",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Stability Ball"],
    primaryMuscles: ["abs", "obliques"],
    secondaryMuscles: ["glutes", "front_shoulder", "serratus"],
  },
  {
    id: 238,
    name: "Plank Hip Dip",
    category: "Core",
    subcategory: "Plank",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["glutes", "lower_back"],
  },

  // ── CORE → CRUNCH (new) ─────────────────────────────────────────────────
  {
    id: 239,
    name: "Standard Crunch",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip_flexors", "obliques"],
  },
  {
    id: 240,
    name: "Weighted Crunch",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Weight Plate"],
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques", "hip_flexors"],
  },
  {
    id: 241,
    name: "Stability Ball Crunch",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Stability Ball"],
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques", "hip_flexors"],
  },
  {
    id: 242,
    name: "V-Up",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["quads", "obliques"],
  },
  {
    id: 243,
    name: "Sit-Up",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques"],
  },
  {
    id: 244,
    name: "Decline Sit-Up",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Decline Bench"],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques"],
  },
  {
    id: 245,
    name: "Toe-Touch Crunch",
    category: "Core",
    subcategory: "Crunch",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip_flexors", "hamstrings"],
  },

  // ── CORE → STATIC HOLD (new) ────────────────────────────────────────────
  {
    id: 246,
    name: "Hollow Body Rock",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors", "serratus"],
    secondaryMuscles: ["quads", "obliques"],
  },
  {
    id: 247,
    name: "Superman Hold",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings", "rear_shoulder"],
  },
  {
    id: 248,
    name: "Back Extension Hold",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings", "upper_back"],
  },
  {
    id: 249,
    name: "Loaded Carry (Farmer's Walk)",
    category: "Core",
    subcategory: "Static Hold",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Weight Plates"],
    primaryMuscles: ["forearms", "abs", "obliques"],
    secondaryMuscles: ["upper_back", "side_shoulder", "glutes", "calves"],
  },

  // ── CORE → DYNAMIC (new) ────────────────────────────────────────────────
  {
    id: 250,
    name: "Flutter Kicks",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["quads", "obliques"],
  },
  {
    id: 251,
    name: "Scissor Kicks",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["adductors", "quads"],
  },
  {
    id: 252,
    name: "Dead Bug",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques", "lower_back", "front_shoulder"],
  },
  {
    id: 253,
    name: "Bird Dog",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["abs", "lower_back", "glutes"],
    secondaryMuscles: ["obliques", "hamstrings", "rear_shoulder"],
  },
  {
    id: 254,
    name: "Standing Oblique Crunch",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs", "hip_flexors"],
  },
  {
    id: 255,
    name: "Slow Mountain Climbers",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["obliques", "front_shoulder", "quads"],
  },
  {
    id: 256,
    name: "Pallof Press (Band)",
    category: "Core",
    subcategory: "Dynamic",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band"],
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["front_shoulder", "chest", "upper_back"],
  },

  // ── CORE → BACK (new subcategory) ───────────────────────────────────────
  {
    id: 257,
    name: "Back Extension",
    category: "Core",
    subcategory: "Back",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings", "upper_back"],
  },
  {
    id: 258,
    name: "Prone Cobra",
    category: "Core",
    subcategory: "Back",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["lower_back", "rear_shoulder"],
    secondaryMuscles: ["glutes", "upper_back"],
  },
  {
    id: 259,
    name: "Band Good Morning",
    category: "Core",
    subcategory: "Back",
    progressionType: "Band",
    difficulty: "Intermediate",
    equipment: ["Resistance Band"],
    primaryMuscles: ["hamstrings", "lower_back", "glutes"],
    secondaryMuscles: ["abs"],
  },
  {
    id: 260,
    name: "Single-Leg Back Extension",
    category: "Core",
    subcategory: "Back",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings", "obliques"],
  },

  // ── FULL BODY (new) ──────────────────────────────────────────────────────
  {
    id: 261,
    name: "Man Maker",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Dumbbells"],
    primaryMuscles: ["chest", "lats", "quads", "glutes", "shoulders"],
    secondaryMuscles: ["triceps", "biceps", "abs", "hamstrings", "calves"],
  },
  {
    id: 262,
    name: "Turkish Get-Up",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "glutes", "front_shoulder", "quads"],
    secondaryMuscles: ["obliques", "triceps", "lower_back", "hamstrings"],
  },
  {
    id: 263,
    name: "Ape Reach",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "front_shoulder"],
    secondaryMuscles: ["abs", "hamstrings", "upper_back"],
  },
  {
    id: 264,
    name: "Crawl-Through",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["abs", "obliques", "front_shoulder"],
    secondaryMuscles: ["triceps", "chest", "hip_flexors", "glutes"],
  },
  {
    id: 265,
    name: "Devil Press",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Weighted",
    difficulty: "Advanced",
    equipment: ["Dumbbells"],
    primaryMuscles: ["chest", "quads", "glutes", "front_shoulder"],
    secondaryMuscles: ["triceps", "abs", "hamstrings", "calves"],
  },
  {
    id: 266,
    name: "Handstand to Squat",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: [],
    primaryMuscles: ["front_shoulder", "quads", "glutes", "abs"],
    secondaryMuscles: ["triceps", "hamstrings", "calves", "serratus"],
  },
  {
    id: 267,
    name: "Lateral Shuffle",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: [],
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["calves", "abs"],
  },
  {
    id: 268,
    name: "Sprint in Place",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: [],
    primaryMuscles: ["quads", "calves", "hip_flexors"],
    secondaryMuscles: ["glutes", "hamstrings", "abs"],
  },
  {
    id: 269,
    name: "Burpee Muscle-Up",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["chest", "quads", "glutes", "lats", "biceps", "triceps"],
    secondaryMuscles: ["abs", "front_shoulder", "hamstrings", "calves"],
  },
  {
    id: 270,
    name: "Rope Climb",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Climbing Rope"],
    primaryMuscles: ["lats", "biceps", "forearms"],
    secondaryMuscles: ["upper_back", "abs", "quads", "rear_shoulder"],
  },
  {
    id: 271,
    name: "Legless Rope Climb",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Climbing Rope"],
    primaryMuscles: ["lats", "biceps", "forearms", "abs"],
    secondaryMuscles: ["upper_back", "rear_shoulder", "obliques"],
  },
  {
    id: 272,
    name: "Monkey Bar Traverse",
    category: "Full Body",
    subcategory: "Full Body",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Monkey Bars"],
    primaryMuscles: ["lats", "forearms", "upper_back"],
    secondaryMuscles: ["biceps", "abs", "rear_shoulder"],
  },

  // ── FULL BODY → CONDITIONING (new subcategory) ───────────────────────────
  {
    id: 273,
    name: "Jump Rope Singles",
    category: "Full Body",
    subcategory: "Conditioning",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Jump Rope"],
    primaryMuscles: ["calves", "quads"],
    secondaryMuscles: ["abs", "forearms", "front_shoulder"],
  },
  {
    id: 274,
    name: "Jump Rope Double Unders",
    category: "Full Body",
    subcategory: "Conditioning",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Jump Rope"],
    primaryMuscles: ["calves", "quads"],
    secondaryMuscles: ["abs", "forearms", "front_shoulder"],
  },
  {
    id: 275,
    name: "Box Step-Up",
    category: "Full Body",
    subcategory: "Conditioning",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Box"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "abs"],
  },
  {
    id: 276,
    name: "Weighted Box Step-Up",
    category: "Full Body",
    subcategory: "Conditioning",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Box", "Weight Vest"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
  },

  // ── PULL → GRIP / FOREARM (new subcategory) ─────────────────────────────
  {
    id: 277,
    name: "Bar Hang with Weight",
    category: "Pull",
    subcategory: "Grip",
    progressionType: "Weighted",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar", "Weight Belt"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["lats", "biceps", "upper_back"],
  },
  {
    id: 278,
    name: "One-Arm Dead Hang",
    category: "Pull",
    subcategory: "Grip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Pull-Up Bar"],
    primaryMuscles: ["forearms", "lats"],
    secondaryMuscles: ["biceps", "obliques"],
  },
  {
    id: 279,
    name: "Towel Hang",
    category: "Pull",
    subcategory: "Grip",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar", "Towel"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["lats", "biceps"],
  },
  {
    id: 280,
    name: "Pinch Grip Dead Hang",
    category: "Pull",
    subcategory: "Grip",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Weight Plate"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
  },
  {
    id: 281,
    name: "Fat Grip Dead Hang",
    category: "Pull",
    subcategory: "Grip",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Pull-Up Bar", "Fat Gripz"],
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["lats", "biceps"],
  },

  // ── PUSH → RING STRENGTH (new subcategory) ──────────────────────────────
  {
    id: 282,
    name: "Ring Support Hold",
    category: "Push",
    subcategory: "Ring Strength",
    progressionType: "Bodyweight",
    difficulty: "Beginner",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus", "forearms"],
  },
  {
    id: 283,
    name: "Ring Turned Out Support Hold",
    category: "Push",
    subcategory: "Ring Strength",
    progressionType: "Bodyweight",
    difficulty: "Intermediate",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "triceps", "front_shoulder"],
    secondaryMuscles: ["abs", "serratus", "forearms", "biceps"],
  },
  {
    id: 284,
    name: "Ring L-Sit",
    category: "Push",
    subcategory: "Ring Strength",
    progressionType: "Bodyweight",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["abs", "hip_flexors", "triceps", "chest"],
    secondaryMuscles: ["quads", "forearms", "front_shoulder", "serratus"],
  },
  {
    id: 285,
    name: "Ring Iron Cross Progression",
    category: "Push",
    subcategory: "Ring Strength",
    progressionType: "Band",
    difficulty: "Advanced",
    equipment: ["Gymnastic Rings", "Resistance Band"],
    primaryMuscles: ["chest", "lats", "rear_shoulder", "front_shoulder"],
    secondaryMuscles: ["abs", "triceps", "biceps", "serratus"],
  },
  {
    id: 286,
    name: "Iron Cross Hold",
    category: "Push",
    subcategory: "Ring Strength",
    progressionType: "Bodyweight",
    difficulty: "Elite",
    equipment: ["Gymnastic Rings"],
    primaryMuscles: ["chest", "lats", "rear_shoulder", "front_shoulder"],
    secondaryMuscles: ["abs", "triceps", "biceps", "serratus", "forearms"],
  },
]